name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v3

      - name: Azureにログイン
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Bicepファイルのデプロイ
        uses: azure/powershell@v1
        with:
          inlineScript: |
            az deployment group create --resource-group rg-actions-demo --template-file main.bicep
          azPSVersion: "latest"

      - name: Python環境のセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 依存関係のインストール
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t ./deployment-package

      - name: アプリケーションのパッケージ化
        run: |
          cd deployment-package
          zip -r ../app.zip .
          cd ..
          zip -g app.zip main.py

      - name: Azure App Serviceへのデプロイ
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-actions-sample
          resource-group: rg-actions-demo
          package: ./app.zip
