# .github/workflows/cd.yml
name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v3

      - name: Azureにログイン
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Bicepファイルのデプロイ
        uses: azure/powershell@v1
        with:
          inlineScript: |
            az deployment group create --resource-group rg-actions-demo --template-file main.bicep
          azPSVersion: "latest"

      - name: アプリケーションのパッケージ化
        run: |
          zip -r app.zip .

      - name: Azure App Serviceへのデプロイ
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-actions-sample
          resource-group: rg-actions-demo
          package: ./app.zip
